---
# Per environment values which override defaults in hmpps-person-integration-api/values.yaml

generic-service:
  ingress:
    host: person-integration-api.hmpps.service.justice.gov.uk

  env:
    HMPPS_AUTH_URL: "https://sign-in.hmpps.service.justice.gov.uk/auth"
    PRISON_API_BASE_URL: "https://prison-api.prison.service.justice.gov.uk"
    DOCUMENT_API_BASE_URL: "https://document-api.hmpps.service.justice.gov.uk"

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  alertSeverity: hmpps-person-integration-api-prod
