name: Pipeline [test -> build -> deploy]

on:
  push:
    branches:
      - '**'

  workflow_dispatch:
    inputs:
      environment:
        description: Environment
        type: choice
        required: true
        options:
          - development
          - preprod
          - staging
          - production
        default: 'development'
      docker_registry:
        description: Docker registry
        required: true
        default: 'ghcr.io'
        type: choice
        options:
          - 'ghcr.io'
          - 'quay.io'
      registry_org:
        description: Docker registry organisation
        required: true
        default: 'ministryofjustice'
        type: choice
        options:
          - 'ministryofjustice'
          - 'hmpps'
      additional_docker_tag:
        description: Additional docker tag that can be used to specify stable tags
        required: false
        default: ''
        type: string
      push:
        description: Push docker image to registry flag
        required: true
        default: true


permissions:
  contents: read
  packages: write

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2
        with:
          persist-credentials: false
      - name: Set up Python
        uses: actions/setup-python@v5.6.0
        with:
          python-version: '3.11'
      - name: Set Python hash
        run: echo "PY=$(python -VV | sha256sum | cut -d' ' -f1)" >> $GITHUB_ENV
      - name: Cache pre-commit environments
        uses: actions/cache@v4.2.3
        with:
          path: ~/.cache/pre-commit
          key: pre-commit|${{ env.PY }}|${{ hashFiles('.pre-commit-config.yaml') }}
      - name: Run pre-commit hooks
        uses: pre-commit/action@v3.0.1

  helm_lint:
    name: helm lint
    uses: ministryofjustice/hmpps-github-actions/.github/workflows/test_helm_lint.yml@v2 # WORKFLOW VERSION
    secrets: inherit
    with:
      environment: ${{ inputs.environment || 'development' }}

  kotlin_validate:
    name: Validate the kotlin
    uses: ministryofjustice/hmpps-github-actions/.github/workflows/kotlin_validate.yml@v2 # WORKFLOW_VERSION
    secrets: inherit

  build:
    name: Build docker image from hmpps-github-actions
    if: github.ref == 'refs/heads/main'
    uses: ministryofjustice/hmpps-github-actions/.github/workflows/docker_build.yml@v2 # WORKFLOW_VERSION
    needs:
      - kotlin_validate
    with:
      docker_registry: ${{ inputs.docker_registry || 'ghcr.io' }}
      registry_org: ${{ inputs.registry_org || 'ministryofjustice' }}
      additional_docker_tag: ${{ inputs.additional_docker_tag }}
      push: ${{ inputs.push || true }}
      docker_multiplatform: false

  deploy_dev:
    name: Deploy to dev environment
    needs:
      - build
      - helm_lint
    uses: ministryofjustice/hmpps-github-actions/.github/workflows/deploy_env.yml@v2 # WORKFLOW_VERSION
    secrets: inherit
    with:
      environment: 'development'
      app_version: '${{ needs.build.outputs.app_version }}'

  deploy_preprod:
    name: Deploy to pre-production environment
    needs:
      - build
      - deploy_dev
    uses: ministryofjustice/hmpps-github-actions/.github/workflows/deploy_env.yml@v2 # WORKFLOW_VERSION
    secrets: inherit
    with:
      environment: 'preprod'
      app_version: '${{ needs.build.outputs.app_version }}'

  deploy_production:
    name: Deploy to production environment
    needs:
      - build
      - deploy_preprod
    uses: ministryofjustice/hmpps-github-actions/.github/workflows/deploy_env.yml@v2 # WORKFLOW_VERSION
    secrets: inherit
    with:
      environment: 'production'
      app_version: '${{ needs.build.outputs.app_version }}'
